name=PioBadge
version=1.0.0
author=Coding Lambda
maintainer=Coding Lambda <none@example.com>
sentence=This library allows development for PyBadge using PlatformIO.
paragraph=This library allows development for PyBadge using PlatformIO. Sadly Adafruit Arcada does not work with PlatformIO.
category=Display
url=https://github.com/Coding-Lambda/PioBadge
architectures=*
depends=Adafruit ImageReader Library, Adafruit NeoPixel, Adafruit ST7735 and ST7789 Library, Adafruit SPIFlash, Adafruit LIS3DH, SdFat - Adafruit Fork, Audio - Adafruit Fork